travis:
  secure:
    BINSTAR_TOKEN: BWPDfT/YiRO79p62QIIlxDEMuuEkqnDh0P396vau6zenY1ogOW8RjNeYC53KK4KrKXn/3MXL7wUczFCXX0k61jBQmOiukqDM20N843MQRTVfh+OZdneKz1izCCcMU0LmCFRWRCjL9tP9VOZtKkaOKi2HkqP64BzvgaJBxoIPWjXTqIbJxXZGoRMjPveVWyijQoJCG15gQDjSygOPjJTLzwqL1O26tKc/qRONomPlMw3XpDoCXAWrXAlTa4dvfu5dt2iPyKILB521TIkB12jnfBxxnVCZgCn+K5uB2UaDqDtENEg+rPnF1eXhMssn8vsOfK4ISIxvha2e3HsIjT/kUgogZGgEHPFeM85r2RIL5ro9LRq8zDuLG630wMOBlfzyrsq3zHrFv/MHpVGdhVCfhCb1CdXi9zJU/+cMOMUV7cGWBXvw2OeM0Ulkwqa3Ra5xiq5dfMvRP7jj2bFCD/9N0OyoOodsIDb0xF/7blmq+L+P6pI24WEO/I8BSnWahF32Al3NQH1oH2+BNS3JBaTbOJfCuoghwX+POrYeU/p2SHeLmRWWUMWeO2c2v6NUb1PwKORNtu1JtXXiJPQ6a6aRCqzFsCLZ8rUniQuUUQ6k8VI+zSTLwsIAd4Ou3h1Z2S4Af01UxKqkvyGkSAV5a2vPhIvndvkBP59UvgiJ1yBJwck=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
